LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := wfd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := bin/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libapedec.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libhevcdec.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libjesancache.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libOMX_Core.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libomxvpu_dec.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libomxvpu_enc.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librk_audio.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librk_demux.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librk_hevcdec.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libRkOMX_Resourcemanager.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librkswscale.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librk_vpuapi.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librkwmapro.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libstagefrighthw.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libjpeghwdec.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libjpeghwenc.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_SRC_FILES := lib/$(TARGET_ARCH)/$(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

